### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by nick-stebbings** [HabFract/monorepo#5]
For mobile experience to be smoother and more intuitive, there are many things that can be adjusted:

- [x] The 'expand' button under the menu is the way to expand to full menu with  text descriptions. Clicking it again shrinks the menu back to the collapsed, minimised form. That is all that can be done to change menu position. This makes designing other pages easier.
- [x] Limit the number of Sphere to 4 maximum, and make it so that the size of the menu icons is never impinging on the top card of a list, the top part of a form.
- [x] Fix the opacity of the menu so that text/background contrast makes it legible

## Spheres List.
- [ ] ~~This should now be a 'spheres breakdown', with a box plot at the top which shows the size of each sphere relative to each other.~~ #33 
- [ ] ~~The vis here should give a sense of the balancing of the number of habits (like the pie chart but for intra-spere series). Later it could be adjusted to account for scale to edit the vis, or filtered by the scale so that we see how many of each scale of each orbit are in each sphere~~ #33 
- [x] Underneath the sphere breakdown vis should be a smaller tabular list of icons (with no description). so that they can not be as blocky/boxy as they are now with the big list of actions

## Orbits Breakdown
- [ ] #34
~~It might be better to move the add orbit button to the right of the vis card~~

## Other fixes needed
- [ ] #27
- [x] Currently if there are no orbits for a sphere on the breakdown page, it has a blank donut chart. it should have a message saying that an orbit needs to be created first.
- [ ] #28
 
## Overall Navigation and Context
- [x] The logo is covering certain forms and should not be the way of going 'home'. That should be done by a back button, (and not dropping into more than one level of context at a time)
- The overall context of lists is not easy to navigate down and up into and away from.  A back button in the obvious place should be used to remove context when the user wants to go back up the page hierarchy

- [ ] #37
- [ ] #36

- ~~ The spheres breakdown page could have a symbol of 4 squares with rounded corners.~~ #37

- [ ] #35
- [x] Remove the 'Visualise' button from the Orbit cards as this is broken currently and won't be the main way of visualising.
- [ ] ~~There is no modal when a sphere or orbit is due to be deleted~~  #14 
- [x] Disabled buttons can be clicked anyway so they are not actually disabled.

// Further thinking that could be turned into issues:

- [ ] #38

- [ ] ~~The scale of the orbit should have the icons rearranged, colour coded in line with the cards of that type, so that people can easily sort them in their mind.~~
- [ ] ~~There should only be two, astronomic and atomic, but when the atomic has a list then it has a few smaller circles arranged around it's circumference. The scale meter underneath the icons should be full up from the left, with the biggest being when there are no atomic or subatomic orbits attached underneath. The smallest in the scale would be the one with the most subatomic orbits. ~~

**Comment by nick-stebbings** [comment]
This is just a list of issues/improvements that are deemed necessary before we do a first release to improve the UX considerably.

If you want to make suggestions on UX, here is the place to do it. I have also listed a few bugs here which I will separate out into issues.

**Comment by nick-stebbings** [comment]
Refactored into more tangible/actionable issues

**Comment by nick-stebbings** [comment]
Refactored into more tangible/actionable issues
